# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('consent_text', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('consented_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='GDPRDataBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('affected_users', models.IntegerField(default=0)),
                ('data_categories', models.JSONField(default=list)),
                ('discovered_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('mitigation_actions', models.TextField(blank=True)),
                ('authority_notified', models.BooleanField(default=False)),
                ('users_notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='GDPRDataDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='GDPRDataRectification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_updated', models.JSONField()),
                ('rectified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegulatorySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('response', models.TextField(blank=True)),
            ],
        ),
    ]
