# Generated by Django 4.2.7 on 2026-01-05 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_domestictransfer_id'),
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_reason', models.CharField(choices=[('large_cash_transaction', 'Large Cash Transaction (> GHS 50,000)'), ('structured_transactions', 'Structured Transactions'), ('unusual_pattern', 'Unusual Transaction Pattern'), ('high_risk_country', 'High Risk Country'), ('pep_involvement', 'Politically Exposed Person'), ('sanctions_match', 'Sanctions List Match'), ('rapid_movement', 'Rapid Movement of Funds'), ('third_party_funding', 'Third Party Funding'), ('other', 'Other')], max_length=50)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('reported', 'Reported to FIC'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_to_fic_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('fic_reference', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sars', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sars', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity Report',
                'verbose_name_plural': 'Suspicious Activity Reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='BOGMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('report_data', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged by BoG')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bog_reference', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_bog_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BoG Monthly Report',
                'verbose_name_plural': 'BoG Monthly Reports',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
