# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.supportticket'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_paymentlog_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backupverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user'], name='accounts_us_user_id_ccfedd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['event_type'], name='accounts_us_event_t_a47a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4de55c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender'], name='accounts_tr_sender__58b222_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recipient'], name='accounts_tr_recipie_e12c70_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='accounts_tr_created_b2c597_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='accounts_tr_status_9c451f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='accounts_su_user_id_6e2a91_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='accounts_su_status_5a9471_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='accounts_se_user_id_9333ce_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['ip_address'], name='accounts_se_ip_addr_458b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['device_id'], name='accounts_se_device__1f38ed_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['created_at'], name='accounts_se_created_e175c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', 'status'], name='accounts_pa_merchan_7c981b_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='accounts_pa_created_754979_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['device_id'], name='accounts_au_device__40ca48_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['ip_address'], name='accounts_au_ip_addr_14f231_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['user'], name='accounts_au_user_id_862faa_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['admin', 'timestamp'], name='accounts_ad_admin_i_93c977_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['action_type', 'timestamp'], name='accounts_ad_action__341dbc_idx'),
        ),
    ]
