# Generated by Django 4.2.7 on 2025-12-18 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_provider', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money')], max_length=20, null=True)),
                ('recipient_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile', 'Mobile Money')], default='mobile', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_re_user_id_287985_idx'), models.Index(fields=['recipient_type'], name='accounts_re_recipie_eecbb1_idx')],
            },
        ),
    ]
