# Generated by Django 4.2.7 on 2025-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
