# Generated by Django 4.2.7 on 2025-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recipient_bank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action_type',
            field=models.CharField(choices=[('user_mod', 'User Modification'), ('payment_override', 'Payment Override'), ('settings_change', 'System Settings Change'), ('access_control', 'Access Control Change'), ('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('transaction', 'Transaction'), ('verification', 'Verification Submitted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='backupverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='backupverification',
            name='verification_type',
            field=models.CharField(choices=[('db', 'Database'), ('media', 'Media Files'), ('logs', 'Log Files'), ('full', 'Full Backup')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('send', 'Send'), ('request', 'Request'), ('transfer', 'Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='event_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('transaction', 'Transaction'), ('verification', 'Verification Submitted')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
