# Generated by Django 4.2.7 on 2026-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_product_store_alter_adminactivity_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('mobile', 'Mobile Money'), ('sikaremit', 'SikaRemit Account')], default='mobile', max_length=10),
        ),
    ]
