# Generated by Django 4.2.7 on 2026-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_recipient_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='mobile_provider',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money'), ('g_money', 'G-Money')], max_length=20, null=True),
        ),
    ]
