# Generated by Django 4.2.7 on 2026-02-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payout_recipient_fields'),
        ('accounts', '0007_alter_recipient_mobile_provider'),
    ]

    operations = [
    ]
