# Generated by Django 4.2.7 on 2026-02-11 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_rename_users_admin_log_user_time_idx_users_admin_admin_u_805012_idx_and_more'),
        ('merchants', '0003_rename_merchantcustomer_merchantcustomerlegacy_and_more'),
        ('accounts', '0008_merge_20260209_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('transactions', 'Transactions'), ('users', 'Users'), ('revenue', 'Revenue'), ('payments', 'Payments'), ('merchants', 'Merchants'), ('compliance', 'Compliance'), ('customers', 'Customers'), ('disputes', 'Disputes'), ('audit', 'Audit Trail'), ('performance', 'Performance')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('filters', models.JSONField(default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('transaction', 'Transaction Summary'), ('revenue', 'Revenue Report'), ('customer', 'Customer Analysis'), ('payment_methods', 'Payment Methods'), ('geographic', 'Geographic Distribution')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='generating', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=20)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('transaction', 'Transaction Summary'), ('revenue', 'Revenue Report'), ('customer', 'Customer Analysis'), ('payment_methods', 'Payment Methods'), ('geographic', 'Geographic Distribution')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=10)),
                ('email_recipients', models.JSONField(default=list)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='accounts_pa_recipie_ad2f8e_idx',
            old_name='accounts_payout_recipient_email_idx',
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scheduled_reports', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reporttemplate'),
        ),
        migrations.AddIndex(
            model_name='reportgenerationjob',
            index=models.Index(fields=['status', 'created_at'], name='accounts_re_status_a63afd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgenerationjob',
            index=models.Index(fields=['job_type', 'object_id'], name='accounts_re_job_typ_944938_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['cache_key'], name='accounts_re_cache_k_8b95d2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['expires_at'], name='accounts_re_expires_cc690e_idx'),
        ),
        migrations.AddField(
            model_name='merchantreport',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantreport',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.reporttemplate'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='users.customer'),
        ),
        migrations.AddField(
            model_name='adminreport',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['status', 'next_run'], name='accounts_sc_status_ce0e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['merchant'], name='accounts_sc_merchan_33a82d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['admin_user'], name='accounts_sc_admin_u_11f4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantreport',
            index=models.Index(fields=['merchant', '-created_at'], name='accounts_me_merchan_46a2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantreport',
            index=models.Index(fields=['status'], name='accounts_me_status_6463ca_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantreport',
            index=models.Index(fields=['report_type'], name='accounts_me_report__6d9fed_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['customer', '-created_at'], name='accounts_cu_custome_68cd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['status'], name='accounts_cu_status_d479e8_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['start_date', 'end_date'], name='accounts_cu_start_d_5879a2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['admin_user', '-created_at'], name='accounts_ad_admin_u_74cde3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['status'], name='accounts_ad_status_204d60_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['report_type'], name='accounts_ad_report__8308a3_idx'),
        ),
    ]
