# Generated by Django 4.2.7 on 2026-03-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminreport_customerstatement_merchantreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money'), ('g_money', 'G-Money')], max_length=50),
        ),
    ]
