# Generated by Django 4.2.7 on 2026-03-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_payout_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_blacklisted_token',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='refresh_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_key',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_key'], name='accounts_se_session_6583e0_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['refresh_token'], name='accounts_se_refresh_ad84ba_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expiry_date'], name='accounts_se_expiry__83fbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_active'], name='accounts_se_is_acti_339f60_idx'),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='auth_blackl_token_e0c274_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['user'], name='auth_blackl_user_id_d40463_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['expires_at'], name='auth_blackl_expires_b577d7_idx'),
        ),
    ]
