# Generated by Django 4.2.7 on 2026-01-05 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_alter_domestictransfer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('payment', 'Payment Service'), ('balance', 'Balance Check'), ('transfer', 'Money Transfer'), ('airtime', 'Airtime Purchase'), ('bill_payment', 'Bill Payment'), ('custom', 'Custom Service')], default='payment', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('menu_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('service_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_menu', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('menu_history', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='USSDTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_code', models.CharField(max_length=50)),
                ('current_menu', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('menu_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_transactions', to='payments.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ussd.ussdsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['phone_number', 'status'], name='ussd_ussdse_phone_n_76b286_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['session_id'], name='ussd_ussdse_session_52f2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['status', 'last_activity'], name='ussd_ussdse_status_a9a95b_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['phone_number', 'status'], name='ussd_ussdtr_phone_n_139154_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['session', 'created_at'], name='ussd_ussdtr_session_7f01ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['status', 'created_at'], name='ussd_ussdtr_status_dd048b_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['service_code'], name='ussd_ussdtr_service_b0a9d2_idx'),
        ),
    ]
