# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('payment', 'Payment'), ('security', 'Security')], default='info', max_length=10)),
                ('notification_type', models.CharField(blank=True, choices=[('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_successful', 'Payment Successful'), ('payment_pending', 'Payment Pending'), ('withdrawal', 'Withdrawal'), ('withdrawal_failed', 'Withdrawal Failed'), ('transfer_sent', 'Transfer Sent'), ('transfer_received', 'Transfer Received'), ('transfer_failed', 'Transfer Failed'), ('account_registered', 'Account Registered'), ('account_verified', 'Account Verified'), ('login_successful', 'Login Successful'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_pending', 'KYC Pending'), ('merchant_application_submitted', 'Merchant Application Submitted'), ('merchant_application_approved', 'Merchant Application Approved'), ('merchant_application_rejected', 'Merchant Application Rejected'), ('merchant_invitation_sent', 'Merchant Invitation Sent'), ('merchant_invitation_accepted', 'Merchant Invitation Accepted'), ('merchant_invitation_expired', 'Merchant Invitation Expired'), ('merchant_account_created', 'Merchant Account Created'), ('merchant_payment_received', 'Merchant Payment Received'), ('merchant_withdrawal', 'Merchant Withdrawal'), ('security_login_from_new_device', 'Login from New Device'), ('security_suspicious_activity', 'Suspicious Activity Detected'), ('security_account_locked', 'Account Locked'), ('security_password_expired', 'Password Expired'), ('security_api_key_created', 'API Key Created'), ('security_api_key_revoked', 'API Key Revoked'), ('system_maintenance', 'System Maintenance'), ('system_update', 'System Update'), ('admin_message', 'Admin Message'), ('promotional_offer', 'Promotional Offer'), ('wallet_topup', 'Wallet Top-up'), ('wallet_low_balance', 'Low Balance Warning'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('remittance_sent', 'Remittance Sent'), ('remittance_received', 'Remittance Received'), ('remittance_failed', 'Remittance Failed'), ('exchange_rate_update', 'Exchange Rate Update')], max_length=30, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_received', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('web', 'Web')], default='web', max_length=10)),
                ('category', models.CharField(choices=[('scheduled', 'Scheduled'), ('expiring', 'Expiring'), ('actionable', 'Actionable')], default='', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actions', models.JSONField(default=list)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('delivery_metrics', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('web_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
