# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.reporttemplate'),
        ),
        migrations.AddField(
            model_name='report',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.reporttemplate'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.store'),
        ),
        migrations.AddField(
            model_name='merchantverificationdocument',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantverificationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantsettings',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantpayoutsettings',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantonboarding',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantnotificationsettings',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantinvitation',
            name='merchant_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantcustomer',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants_merchant_customers', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='merchantcustomer',
            unique_together={('merchant', 'customer_email')},
        ),
    ]
