# Generated by Django 4.2.7 on 2025-12-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_kycdocument_document_type_and_more'),
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MerchantCustomer',
            new_name='MerchantCustomerLegacy',
        ),
        migrations.AlterModelTable(
            name='merchantcustomerlegacy',
            table='merchants_merchantcustomer',
        ),
    ]
