# Generated by Django 4.2.7 on 2026-02-11 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_rename_users_admin_log_user_time_idx_users_admin_admin_u_805012_idx_and_more'),
        ('merchants', '0003_rename_merchantcustomer_merchantcustomerlegacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_scheduled_reports', to='users.merchant'),
        ),
    ]
