# Generated by Django 4.2.7 on 2026-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_scheduledreport_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product main image', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Product thumbnail (auto-generated)', null=True, upload_to='product_thumbnails/'),
        ),
    ]
