# Generated by Django 4.2.7 on 2026-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_add_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category for customer browsing', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this product on homepage'),
        ),
        migrations.DeleteModel(
            name='productgallery',
        ),
    ]
