# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['provider'], name='payments_ve_provide_ba87a7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['success'], name='payments_ve_success_f559e9_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['created_at'], name='payments_ve_created_571e90_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['phone_number'], name='payments_ve_phone_n_7d6e82_idx'),
        ),
        migrations.AddField(
            model_name='ussdtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='ussdtransaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.ussdsession'),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ussdmenu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ussdmenu'),
        ),
        migrations.AddIndex(
            model_name='ussdanalytics',
            index=models.Index(fields=['date', 'network'], name='payments_us_date_abdc7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ussdanalytics',
            unique_together={('date', 'network')},
        ),
        migrations.AddField(
            model_name='transactionanalytics',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='transactionanalytics',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='telecomprovider',
            name='country',
            field=models.ForeignKey(help_text='Country where this provider operates', on_delete=django.db.models.deletion.CASCADE, related_name='telecom_providers', to='payments.country'),
        ),
        migrations.AddField(
            model_name='telecompackage',
            name='currency',
            field=models.ForeignKey(help_text='Currency for the package price', on_delete=django.db.models.deletion.PROTECT, related_name='telecom_packages', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='telecompackage',
            name='provider',
            field=models.ForeignKey(help_text='Telecom provider offering this package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='payments.telecomprovider'),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscriptionfeature'),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptiondiscount',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, to='payments.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simpleussdtransaction',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='scheduledpayout',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_transactions', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscriptionfeature'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='payments.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_paymentlog_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='merchantfeeoverride',
            name='fee_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.feeconfiguration'),
        ),
        migrations.AddField(
            model_name='merchantfeeoverride',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_overrides', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='merchantfeeoverride',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_override_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantfeeoverride',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_override_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantanalytics',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fee_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text="If set, this is a merchant-specific fee. If null, it's platform-wide.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_configurations', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='feecalculationlog',
            name='fee_configuration',
            field=models.ForeignKey(help_text='Fee configuration used for calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.feeconfiguration'),
        ),
        migrations.AddField(
            model_name='feecalculationlog',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant involved (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchant'),
        ),
        migrations.AddField(
            model_name='feecalculationlog',
            name='user',
            field=models.ForeignKey(help_text='User who initiated the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='currencypreference',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_for_users', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='currencypreference',
            name='display_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_for_users', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='currencypreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossborderremittance',
            name='exemption_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossborderremittance',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_remittances', to='users.customer'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Primary currency used in this country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country this rule applies to (for country scope)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='payments.country'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency this rule applies to (for currency scope)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='telecom_provider',
            field=models.ForeignKey(blank=True, help_text='Provider this rule applies to (for provider scope)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='payments.telecomprovider'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_type', 'period_start', 'period_end'], name='payments_an_metric__cad45b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['frequency', 'calculated_at'], name='payments_an_frequen_dcb3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['is_active', 'metric_type'], name='payments_an_is_acti_b79119_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletbalance',
            unique_together={('user', 'currency')},
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['transaction_id'], name='payments_us_transac_ce31d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['session', 'status'], name='payments_us_session_8acac8_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdtransaction',
            index=models.Index(fields=['created_at'], name='payments_us_created_855273_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['session_id'], name='payments_us_session_25dced_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['msisdn', 'state'], name='payments_us_msisdn_aaca9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['expires_at'], name='payments_us_expires_4cbba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ussdmenu',
            unique_together={('menu_type', 'language', 'is_default')},
        ),
        migrations.AddIndex(
            model_name='transactionanalytics',
            index=models.Index(fields=['transaction_type', 'created_at'], name='payments_tr_transac_99a272_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalytics',
            index=models.Index(fields=['merchant', 'created_at'], name='payments_tr_merchan_1879cc_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalytics',
            index=models.Index(fields=['status', 'created_at'], name='payments_tr_status_7750b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalytics',
            index=models.Index(fields=['country_from', 'country_to'], name='payments_tr_country_d599f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalytics',
            index=models.Index(fields=['created_at', 'amount'], name='payments_tr_created_639cb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telecomprovider',
            unique_together={('code', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='telecompackage',
            unique_together={('provider', 'package_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionusage',
            unique_together={('subscription', 'feature', 'period_start')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'plan')},
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['merchant', 'created_at'], name='payments_po_merchan_169324_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['device_id'], name='payments_po_device__8d5f27_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['status'], name='payments_po_status_b408e1_idx'),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['merchant', 'status'], name='payments_po_merchan_683797_idx'),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['device_type'], name='payments_po_device__56ae81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together={('plan', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='merchantfeeoverride',
            unique_together={('merchant', 'fee_configuration', 'status')},
        ),
        migrations.AddIndex(
            model_name='merchantanalytics',
            index=models.Index(fields=['merchant', 'date'], name='payments_me_merchan_3e6508_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantanalytics',
            index=models.Index(fields=['date', 'transaction_value'], name='payments_me_date_d76bc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantanalytics',
            unique_together={('merchant', 'date')},
        ),
        migrations.AddIndex(
            model_name='feeconfiguration',
            index=models.Index(fields=['fee_type', 'is_active'], name='payments_fe_fee_typ_17c3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='feeconfiguration',
            index=models.Index(fields=['merchant', 'fee_type', 'is_active'], name='payments_fe_merchan_9c168c_idx'),
        ),
        migrations.AddIndex(
            model_name='feeconfiguration',
            index=models.Index(fields=['corridor_from', 'corridor_to', 'fee_type'], name='payments_fe_corrido_e3d2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='feeconfiguration',
            index=models.Index(fields=['effective_from', 'effective_to'], name='payments_fe_effecti_9a5bc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeconfiguration',
            unique_together={('fee_type', 'merchant', 'corridor_from', 'corridor_to', 'is_active', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='feecalculationlog',
            index=models.Index(fields=['transaction_type', 'calculated_at'], name='payments_fe_transac_5021d7_idx'),
        ),
        migrations.AddIndex(
            model_name='feecalculationlog',
            index=models.Index(fields=['merchant', 'calculated_at'], name='payments_fe_merchan_f0b206_idx'),
        ),
        migrations.AddIndex(
            model_name='feecalculationlog',
            index=models.Index(fields=['calculated_at'], name='payments_fe_calcula_8ba7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'timestamp'], name='payments_ex_from_cu_509de2_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['is_latest'], name='payments_ex_is_late_f01317_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['timestamp'], name='payments_ex_timesta_f73e36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'status'], name='payments_bi_user_id_d352c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_reference'], name='payments_bi_bill_re_54a873_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['due_date'], name='payments_bi_due_dat_6f2fad_idx'),
        ),
    ]
