# Generated by Django 4.2.7 on 2025-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_domestic_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictransfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
