# Generated by Django 4.2.7 on 2026-01-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_webhook_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictransfer',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod'),
        ),
    ]
