# Generated by Django 4.2.7 on 2026-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_allow_null_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
