# Generated by Django 4.2.7 on 2026-01-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
        ('payments', '0007_delete_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossborderremittance',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_remittances', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='domestictransfer',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_domestic_transfers', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
    ]
