# Generated by Django 4.2.7 on 2026-01-25 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_alter_crossborderremittance_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('remittance', 'Remittance'), ('bill', 'Bill Payment'), ('other', 'Other')], default='other', max_length=20)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_account', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('biller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_due_date', models.DateField(blank=True, null=True)),
                ('mobile_money_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_paymentlog_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
