# Generated by Django 4.2.7 on 2026-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_add_dispute_enhancements'),
        ('payments', 'auto_populate_telecom'),
    ]

    operations = [
    ]
