# Generated by Django 4.2.7 on 2026-02-11 03:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_update_bill_transaction_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airteltigo', 'AirtelTigo Money'), ('glo', 'Glo Cash')], max_length=15)),
                ('mobile_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('mobile_money_transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_prompt', 'Prompt Sent'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=15)),
                ('prompt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('network_response', models.JSONField(default=dict)),
                ('confirmation_code', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nfc_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('mobile_wallet', 'Mobile Wallet'), ('wearable', 'Wearable Device')], max_length=20)),
                ('nfc_id', models.CharField(max_length=100, unique=True)),
                ('card_token', models.CharField(blank=True, max_length=200)),
                ('wallet_provider', models.CharField(blank=True, max_length=50)),
                ('reader_id', models.CharField(max_length=50)),
                ('reader_type', models.CharField(max_length=30)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('cryptogram', models.TextField(blank=True)),
                ('aic', models.CharField(blank=True, max_length=10)),
                ('un', models.CharField(blank=True, max_length=20)),
                ('nfc_data', models.JSONField(default=dict)),
                ('emv_tags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartphonePOSDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_model', models.CharField(max_length=100)),
                ('os_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('os_version', models.CharField(max_length=20)),
                ('app_version', models.CharField(max_length=20)),
                ('device_id_hash', models.CharField(max_length=200, unique=True)),
                ('encryption_key', models.CharField(blank=True, max_length=200)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('pin_required', models.BooleanField(default=True)),
                ('nfc_capable', models.BooleanField(default=False)),
                ('bluetooth_capable', models.BooleanField(default=True)),
                ('camera_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost/Stolen'), ('damaged', 'Damaged'), ('decommissioned', 'Decommissioned')], default='active', max_length=15)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('storage_available', models.BigIntegerField(blank=True, null=True)),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_timestamp', models.DateTimeField(blank=True, null=True)),
                ('security_events', models.JSONField(default=list)),
                ('last_security_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='posdevice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='postransaction',
            name='payments_po_device__8d5f27_idx',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='response_data',
        ),
        migrations.AddField(
            model_name='posdevice',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='biometric_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='certification_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='connection_type',
            field=models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'WiFi'), ('usb', 'USB'), ('nfc', 'NFC'), ('audio_jack', 'Audio Jack'), ('internet', 'Internet')], default='internet', max_length=15),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='emv_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='encryption_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='hardware_specs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='pci_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='pin_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='security_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('enhanced', 'Enhanced'), ('pci_compliant', 'PCI Compliant')], default='standard', max_length=15),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='supports_chip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='supports_contactless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='supports_mobile_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='supports_nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='supports_swipe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='approval_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='biometric_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='card_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.posdevice'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='emv_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='entry_mode',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('chip', 'Chip'), ('swipe', 'Swipe'), ('contactless', 'Contactless'), ('nfc', 'NFC'), ('qr_scan', 'QR Scan'), ('mobile_app', 'Mobile App')], default='manual', max_length=15),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='mobile_money_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='mobile_network',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='nfc_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('nfc_credit', 'NFC Credit Card'), ('nfc_debit', 'NFC Debit Card'), ('mobile_wallet', 'Mobile Wallet'), ('mtn_money', 'MTN Mobile Money'), ('telecel_cash', 'Telecel Cash'), ('airtel_tigo_money', 'AirtelTigo Money'), ('qr_payment', 'QR Payment'), ('upi', 'UPI Payment')], default='credit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='pin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='pos_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='processor_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='response_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='signature_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='signature_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='wallet_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card (Stripe/Paystack)'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money'), ('g_money', 'G-Money'), ('qr', 'QR Payment'), ('mobile_money', 'Mobile Money'), ('sikaremit_balance', 'SikaRemit Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='device_type',
            field=models.CharField(choices=[('smartphone_pos', 'Smartphone POS'), ('nfc_reader', 'NFC Reader'), ('virtual_terminal', 'Virtual Terminal'), ('mobile_reader', 'Mobile Reader'), ('countertop', 'Countertop Terminal'), ('integrated', 'Integrated POS'), ('kiosk', 'Self-Service Kiosk'), ('tablet_pos', 'Tablet POS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('chargeback', 'Chargeback')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('void', 'Void'), ('pre_auth', 'Pre-Authorization'), ('capture', 'Capture'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telecompackage',
            name='data_amount',
            field=models.CharField(blank=True, help_text='Data amount (e.g., 1GB, 500MB, Unlimited)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telecomprovider',
            name='code',
            field=models.CharField(help_text='Unique code for the provider (e.g., MTN, TELECEL)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Code must contain only uppercase letters, numbers, and underscores')]),
        ),
        migrations.AlterField(
            model_name='telecomprovider',
            name='name',
            field=models.CharField(help_text='Provider name (e.g., MTN, Telecel)', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['connection_type'], name='payments_po_connect_8da47d_idx'),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['last_seen'], name='payments_po_last_se_fe774a_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['device', 'created_at'], name='payments_po_device__d85331_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['payment_method'], name='payments_po_payment_673941_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['transaction_id'], name='payments_po_transac_952457_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['mobile_money_transaction_id'], name='payments_po_mobile__5d8d93_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'status'], name='payments_tr_custome_12c55e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant', 'status'], name='payments_tr_merchan_1b01ca_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='payments_tr_transac_1d5140_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='payments_tr_created_02ae92_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='payments_tr_transac_a6e8b9_idx'),
        ),
        migrations.AddField(
            model_name='smartphoneposdevice',
            name='pos_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smartphone_config', to='payments.posdevice'),
        ),
        migrations.AddField(
            model_name='nfcpayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_payment', to='payments.postransaction'),
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_payment', to='payments.postransaction'),
        ),
        migrations.AddIndex(
            model_name='smartphoneposdevice',
            index=models.Index(fields=['device_id_hash'], name='payments_sm_device__e40ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='smartphoneposdevice',
            index=models.Index(fields=['status'], name='payments_sm_status_4bcdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='smartphoneposdevice',
            index=models.Index(fields=['last_heartbeat'], name='payments_sm_last_he_f14329_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcpayment',
            index=models.Index(fields=['nfc_id'], name='payments_nf_nfc_id_ef2484_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcpayment',
            index=models.Index(fields=['wallet_provider'], name='payments_nf_wallet__9765dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['mobile_money_transaction_id'], name='payments_mo_mobile__0ba348_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['mobile_number'], name='payments_mo_mobile__4eb570_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['network'], name='payments_mo_network_5b606d_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['status'], name='payments_mo_status_805dc1_idx'),
        ),
    ]
