# Generated by Django 4.2.7 on 2026-02-27 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_adminactivitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_mobilemoneypayment_nfcpayment_smartphoneposdevice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedBIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(db_index=True, max_length=8, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card (Stripe/Paystack)'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money'), ('g_money', 'G-Money'), ('qr', 'QR Payment'), ('sikaremit_balance', 'SikaRemit Balance')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MultiCurrencyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('conversion_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_source', models.CharField(default='api', max_length=50)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_currency', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Multi-Currency Payment',
                'verbose_name_plural': 'Multi-Currency Payments',
            },
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('investigated', models.BooleanField(default=False)),
                ('investigation_notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('new_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.exchangerate')),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Rate Threshold Alert'), ('change', 'Rate Change Alert'), ('stale', 'Stale Rate Alert')], max_length=20)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('threshold_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change that triggers alert', max_digits=5, null=True)),
                ('notify_emails', models.JSONField(blank=True, default=list, help_text='Additional email addresses to notify')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exchange_rate_alerts', to=settings.AUTH_USER_MODEL)),
                ('notify_users', models.ManyToManyField(blank=True, help_text='Users to notify', related_name='exchange_rate_alert_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate Alert',
                'verbose_name_plural': 'Exchange Rate Alerts',
            },
        ),
        migrations.CreateModel(
            name='FraudBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('email', 'Email Address'), ('ip', 'IP Address'), ('bin', 'Card BIN'), ('device', 'Device Fingerprint'), ('phone', 'Phone Number')], max_length=20)),
                ('entity_value', models.CharField(db_index=True, max_length=255)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_value'], name='payments_fr_entity__bfaebd_idx'), models.Index(fields=['is_active'], name='payments_fr_is_acti_5ff213_idx')],
                'unique_together': {('entity_type', 'entity_value')},
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('risk_score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('risk_level', models.CharField(max_length=20)),
                ('triggered_rules', models.JSONField(default=list)),
                ('transaction_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('false_positive', 'False Positive')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='users.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='payments.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_fr_status_9b7f93_idx'), models.Index(fields=['risk_level'], name='payments_fr_risk_le_5a96c8_idx')],
            },
        ),
    ]
