# Generated by Django 4.2.7 on 2025-12-17 22:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'merchant'), (3, 'customer')], default=3)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('biometric_data', models.JSONField(default=dict)),
                ('verification_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('last_biometric_verify', models.DateTimeField(null=True)),
                ('auth_provider', models.CharField(default='email', max_length=20)),
                ('social_id', models.CharField(blank=True, max_length=255)),
                ('mfa_secret', models.CharField(blank=True, max_length=100)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_backup_codes', models.JSONField(default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='not_started', help_text='KYC verification status for lazy verification flow', max_length=15)),
                ('kyc_started_at', models.DateTimeField(blank=True, help_text='When user first initiated KYC', null=True)),
                ('kyc_completed_at', models.DateTimeField(blank=True, help_text='When KYC was completed', null=True)),
                ('kyc_last_attempt', models.DateTimeField(blank=True, help_text='Last KYC attempt timestamp', null=True)),
                ('first_transaction_attempt', models.DateTimeField(blank=True, help_text='First time user tried to make a transaction', null=True)),
                ('transaction_attempts_count', models.PositiveIntegerField(default=0, help_text='Number of transaction attempts before KYC')),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(null=True)),
                ('address', models.JSONField(default=dict)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('transaction_alerts', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('low_balance_alert', models.BooleanField(default=True)),
                ('balance_threshold', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID'), ('DRIVERS_LICENSE', "Driver's License"), ('UTILITY_BILL', 'Utility Bill')], max_length=20)),
                ('front_image', models.ImageField(upload_to='kyc/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('scan_data', models.JSONField(default=dict)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('is_biller', models.BooleanField(default=False)),
                ('is_subscription_provider', models.BooleanField(default=False)),
                ('is_remittance_agent', models.BooleanField(default=False)),
                ('biller_code', models.CharField(blank=True, max_length=50)),
                ('biller_category', models.CharField(blank=True, max_length=50)),
                ('subscription_terms', models.TextField(blank=True)),
                ('remittance_license', models.CharField(blank=True, max_length=100)),
                ('supported_countries', models.JSONField(default=list)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_merchants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('kyc_required', models.BooleanField(default=True)),
                ('kyc_status', models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='not_started', max_length=20)),
                ('kyc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('last_kyc_check', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_relationship', to='users.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_merchant_customers', to='users.merchant')),
                ('suspended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_merchant_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-onboarded_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantKYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('review_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_factors', models.JSONField(default=list)),
                ('compliance_flags', models.JSONField(default=list)),
                ('kyc_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_submissions', to='users.kycdocument')),
                ('merchant_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='users.merchantcustomer')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merchant_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='users_merch_status_61e99d_idx'), models.Index(fields=['merchant_customer', 'status'], name='users_merch_merchan_fd204c_idx'), models.Index(fields=['review_priority', 'submitted_at'], name='users_merch_review__cf396c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='merchantcustomer',
            index=models.Index(fields=['merchant', 'status'], name='users_merch_merchan_ba563e_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcustomer',
            index=models.Index(fields=['merchant', 'kyc_status'], name='users_merch_merchan_5e8ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcustomer',
            index=models.Index(fields=['status', 'kyc_status'], name='users_merch_status_11a68e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantcustomer',
            unique_together={('merchant', 'customer')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status'], name='users_custo_kyc_sta_196545_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_transaction_attempt'], name='users_custo_first_t_799ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_started_at'], name='users_custo_kyc_sta_a7fd9b_idx'),
        ),
    ]
