# Generated by Django 4.2.7 on 2026-02-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_enhanced_admin_hierarchy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='users_admin_admin_u_805012_idx',
            old_name='users_admin_log_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='users_admin_action_d2e0fd_idx',
            old_name='users_admin_log_action_time_idx',
        ),
        migrations.RenameIndex(
            model_name='adminpermissionoverride',
            new_name='users_admin_admin_p_5da635_idx',
            old_name='users_admin_override_profile_active_idx',
        ),
        migrations.RenameIndex(
            model_name='adminprofile',
            new_name='users_admin_user_id_6d181d_idx',
            old_name='users_admin_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='adminprofile',
            new_name='users_admin_role_id_b507bb_idx',
            old_name='users_admin_role_active_idx',
        ),
        migrations.RenameIndex(
            model_name='adminprofile',
            new_name='users_admin_managed_87b26a_idx',
            old_name='users_admin_managed_by_idx',
        ),
        migrations.RenameIndex(
            model_name='adminsession',
            new_name='users_admin_admin_u_61474c_idx',
            old_name='users_admin_session_user_time_idx',
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Account Created'), ('user_modified', 'User Account Modified'), ('user_suspended', 'User Account Suspended'), ('user_activated', 'User Account Activated'), ('admin_created', 'Admin Account Created'), ('admin_modified', 'Admin Account Modified'), ('admin_suspended', 'Admin Account Suspended'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('kyc_approved', 'KYC Approved'), ('kyc_reJECTED', 'KYC Rejected'), ('merchant_approved', 'Merchant Approved'), ('merchant_rejected', 'Merchant Rejected'), ('transaction_override', 'Transaction Override'), ('system_setting_changed', 'System Setting Changed'), ('emergency_action', 'Emergency Action Taken'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Higher-level admin who manages this admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_admins', to='users.adminprofile'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='permissions_override',
            field=models.JSONField(blank=True, default=list, help_text='Additional permissions beyond role defaults'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='restricted_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Permissions to restrict from this admin'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='permissions',
            field=models.JSONField(default=list, help_text='List of permission keys'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'super_admin'), (2, 'business_admin'), (3, 'operations_admin'), (4, 'verification_admin'), (5, 'merchant'), (6, 'customer')], default=6),
        ),
        migrations.AlterUniqueTogether(
            name='adminpermissionoverride',
            unique_together={('admin_profile', 'permission_key')},
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['timestamp'], name='users_admin_timesta_54a0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['requires_review', 'success'], name='users_admin_require_251a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='users_admin_resourc_9f80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermissionoverride',
            index=models.Index(fields=['expires_at'], name='users_admin_expires_9fe243_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['session_key'], name='users_admin_session_22417b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['is_active', 'expires_at'], name='users_admin_is_acti_7ce3bb_idx'),
        ),
    ]
