# Generated by Django 4.2.7 on 2026-02-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_admin_log_user_time_idx_users_admin_admin_u_805012_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Account Created'), ('user_modified', 'User Account Modified'), ('user_suspended', 'User Account Suspended'), ('user_activated', 'User Account Activated'), ('admin_created', 'Admin Account Created'), ('admin_modified', 'Admin Account Modified'), ('admin_suspended', 'Admin Account Suspended'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('merchant_approved', 'Merchant Approved'), ('merchant_rejected', 'Merchant Rejected'), ('transaction_override', 'Transaction Override'), ('system_setting_changed', 'System Setting Changed'), ('emergency_action', 'Emergency Action Taken'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated')], max_length=100),
        ),
    ]
