# Generated by Django 4.2.7 on 2025-12-17 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFICATION_APPROVE', 'Verification Approved'), ('VERIFICATION_REJECT', 'Verification Rejected'), ('USER_ACTIVATE', 'User Activated'), ('USER_DEACTIVATE', 'User Deactivated'), ('LOGIN', 'User Login'), ('SETTINGS_UPDATE', 'Settings Updated')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='SikaRemit', max_length=100)),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
                ('public_registration', models.BooleanField(default=True)),
                ('bank_transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Flat fee for bank transfers (USD)', max_digits=10)),
                ('mobile_money_fee', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Flat fee for mobile money transfers (USD)', max_digits=10)),
                ('SikaRemit_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee for SikaRemit user transfers (USD)', max_digits=10)),
                ('session_timeout', models.PositiveIntegerField(default=60, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('password_policy', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('strong', 'Strong')], default='strong', max_length=20)),
                ('two_factor_required', models.BooleanField(default=True, help_text='Require 2FA for all admin accounts')),
                ('ip_whitelisting', models.BooleanField(default=False)),
                ('audit_logging', models.BooleanField(default=True)),
                ('api_rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per minute')),
                ('api_timeout', models.PositiveIntegerField(default=30, help_text='API timeout in seconds')),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(default='v1', max_length=10)),
                ('cors_origins', models.JSONField(default=list)),
                ('api_documentation', models.BooleanField(default=True)),
                ('request_logging', models.BooleanField(default=False)),
                ('admin_email_notifications', models.BooleanField(default=True)),
                ('admin_sms_notifications', models.BooleanField(default=False)),
                ('admin_push_notifications', models.BooleanField(default=True)),
                ('error_alerts', models.BooleanField(default=True)),
                ('transaction_alerts', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(blank=True, help_text='Admin notification email', max_length=254)),
                ('transaction_alert_threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('scheduled_maintenance', models.BooleanField(default=False)),
                ('auto_backups', models.BooleanField(default=True)),
                ('log_rotation', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('log_retention_days', models.PositiveIntegerField(default=30)),
                ('max_daily_transactions', models.PositiveIntegerField(default=1000, help_text='Maximum transactions per day per user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
