# Generated by Django 4.2.7 on 2025-12-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Country name', max_length=100)),
                ('flag_emoji', models.CharField(blank=True, help_text='Flag emoji', max_length=10)),
                ('phone_code', models.CharField(blank=True, help_text='Phone country code', max_length=10)),
                ('phone_code_formatted', models.CharField(blank=True, help_text='Formatted phone code', max_length=20)),
                ('currency', models.CharField(blank=True, help_text='Currency name', max_length=100)),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, help_text='Currency symbol', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether country is active for transfers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='core_countr_code_0b5501_idx'), models.Index(fields=['is_active'], name='core_countr_is_acti_9adcd3_idx')],
            },
        ),
    ]
