# Generated by Django 4.2.7 on 2025-12-18 06:15

from django.db import migrations


def create_countries(apps, schema_editor):
    Country = apps.get_model('core', 'Country')
    
    countries_data = [
        {'code': 'US', 'name': 'United States', 'flag_emoji': '🇺🇸', 'phone_code': '+1', 'currency_code': 'USD'},
        {'code': 'GB', 'name': 'United Kingdom', 'flag_emoji': '🇬🇧', 'phone_code': '+44', 'currency_code': 'GBP'},
        {'code': 'CA', 'name': 'Canada', 'flag_emoji': '🇨🇦', 'phone_code': '+1', 'currency_code': 'CAD'},
        {'code': 'AU', 'name': 'Australia', 'flag_emoji': '🇦🇺', 'phone_code': '+61', 'currency_code': 'AUD'},
        {'code': 'DE', 'name': 'Germany', 'flag_emoji': '🇩🇪', 'phone_code': '+49', 'currency_code': 'EUR'},
        {'code': 'FR', 'name': 'France', 'flag_emoji': '🇫🇷', 'phone_code': '+33', 'currency_code': 'EUR'},
        {'code': 'JP', 'name': 'Japan', 'flag_emoji': '🇯🇵', 'phone_code': '+81', 'currency_code': 'JPY'},
        {'code': 'CN', 'name': 'China', 'flag_emoji': '🇨🇳', 'phone_code': '+86', 'currency_code': 'CNY'},
        {'code': 'IN', 'name': 'India', 'flag_emoji': '🇮🇳', 'phone_code': '+91', 'currency_code': 'INR'},
        {'code': 'BR', 'name': 'Brazil', 'flag_emoji': '🇧🇷', 'phone_code': '+55', 'currency_code': 'BRL'},
        {'code': 'MX', 'name': 'Mexico', 'flag_emoji': '🇲🇽', 'phone_code': '+52', 'currency_code': 'MXN'},
        {'code': 'ZA', 'name': 'South Africa', 'flag_emoji': '🇿🇦', 'phone_code': '+27', 'currency_code': 'ZAR'},
        {'code': 'NG', 'name': 'Nigeria', 'flag_emoji': '🇳🇬', 'phone_code': '+234', 'currency_code': 'NGN'},
        {'code': 'EG', 'name': 'Egypt', 'flag_emoji': '🇪🇬', 'phone_code': '+20', 'currency_code': 'EGP'},
        {'code': 'KE', 'name': 'Kenya', 'flag_emoji': '🇰🇪', 'phone_code': '+254', 'currency_code': 'KES'},
        {'code': 'GH', 'name': 'Ghana', 'flag_emoji': '🇬🇭', 'phone_code': '+233', 'currency_code': 'GHS'},
    ]
    
    for country_data in countries_data:
        Country.objects.create(
            code=country_data['code'],
            name=country_data['name'],
            flag_emoji=country_data['flag_emoji'],
            phone_code=country_data['phone_code'],
            currency_code=country_data['currency_code'],
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country'),
    ]

    operations = [
        migrations.RunPython(create_countries),
    ]
