# Generated by Django 4.2.7 on 2026-03-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enhanced_audit_logging'),
        ('core', '0004_populate_countries'),
    ]

    operations = [
    ]
