from django.core.management.base import BaseCommand
from django.utils import timezone
from payments.models.invoices import InvoiceTemplate
from django.contrib.auth import get_user_model

User = get_user_model()

class Command(BaseCommand):
    help = 'Create default invoice templates for existing users'

    def handle(self, *args, **options):
        users_without_templates = User.objects.filter(invoice_templates__isnull=True).distinct()

        templates_created = 0

        for user in users_without_templates:
            # Create a default template for each user
            template, created = InvoiceTemplate.objects.get_or_create(
                user=user,
                name='Default Template',
                defaults={
                    'description': 'Default invoice template',
                    'primary_color': '#2563eb',
                    'secondary_color': '#6b7280',
                    'company_name': f"{user.first_name} {user.last_name}".strip() or user.email,
                    'company_email': user.email,
                    'default_notes': 'Thank you for your business!',
                    'default_terms': 'Payment is due within 30 days of invoice date.',
                    'footer_text': 'Generated by SikaRemit',
                    'is_default': True,
                    'is_active': True,
                }
            )

            if created:
                templates_created += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created default template for {user.email}')
                )

        # Create a system-wide professional template
        professional_template, created = InvoiceTemplate.objects.get_or_create(
            name='Professional Template',
            defaults={
                'description': 'Professional invoice template for businesses',
                'primary_color': '#1f2937',
                'secondary_color': '#6b7280',
                'company_name': 'Your Company Name',
                'company_address': '123 Business Street\nCity, State 12345',
                'company_phone': '(555) 123-4567',
                'company_email': 'billing@yourcompany.com',
                'company_website': 'www.yourcompany.com',
                'default_notes': 'Thank you for your business. We appreciate your prompt payment.',
                'default_terms': 'Payment terms: Net 30 days. Late payments may incur additional charges.',
                'footer_text': 'This invoice was generated electronically and is valid without signature.',
                'is_default': False,
                'is_active': True,
            }
        )

        if created:
            self.stdout.write(
                self.style.SUCCESS('Created professional template')
            )

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {templates_created} default user templates'
            )
        )
